### ISSUE TITLE
Fix the bug of unittest in `SchedulerApp`

### ISSUE THREAD

**Issue by giwon2004** [snu-quiqcl/iquip#124]
From PR #91, we encountered a problem with the' _ExperimentQueueFetcherThread' instance running through the entire app.

This is forcibly destroyed when each unit test ends, and this makes an error.

It needs a fix and is separated from #91 to handle this only.

**Comment by kangz12345** [comment]
Did you find any clue? I'm sorry that I didn't have much time to think about this.

**Comment by giwon2004** [comment]
@BECATRUE and I are trying to fix this. I will try to find more information about the solution.

**Comment by kangz12345** [comment]
Great! Since this makes the unit test abort, it should be fixed as soon as possible.
However, we need some necessary features for our experiment, I decided to develop further even if this issue is not resolved soon.
After implementing the mandatory features, I will take a deeper look in here.
Of course whenever you need some help, please ask me!

**Comment by BECATRUE** [comment]
Wow, I realized that there is no tests about threads in the unittest, so we MUST mock all threads.
Then all errors are resolved!

Sure, we need to implement tests about threads, but now we can resolve this issue through that.
