### ISSUE TITLE
Apply QIWIS v3.0.1

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/iquip#201]
_(updated)_

### Feature you want to implement
Apply the newest QIWIS version.
- Update `frames()` in each app to return with frame titles.
- Add `trust` options in config file if necessary.

**Comment by kangz12345** [comment]
Since we don't have to change any implementation for `qiwis@v2.3.0`, how about applying the change when it is necessary for the later version?
The only thing we can do is changing the GitHub actions, but it does not make any practical difference.
I guess users can just upgrade `qiwis` locally and simply use it.

**Comment by BECATRUE** [comment]
I see! The next version will include setting a frame title, so after done, I will apply the newest version.

**Comment by kangz12345** [comment]
@BECATRUE Could you apply this update?

**Comment by BECATRUE** [comment]
Oh, I planned to update it until tomorrow.
Thanks for notifying me.

**Comment by BECATRUE** [comment]
In QIWIS, I found a bug in snu-quiqcl/qiwis#243, hence I will release the modifed version soon.

This issue is compatible with the updated version, not v3.0.0.
(It works without any error, but shown frame titles are wrong.)
